
# include_recipe 'workstation::bootstrap'
# include_recipe 'workstation::brew-casks'
# include_recipe 'workstation::brew'
# include_recipe 'workstation::shell'
# include_recipe 'workstation::fonts'
# include_recipe 'workstation::plist-entries'
# include_recipe 'workstation::gists'
# include_recipe 'workstation::cleanup'
include_recipe 'workstation::links'
